[package]
name = "epmon_server"
version = "0.1.0"
edition = "2021"

[dependencies]
local-ip-address = "0.6"
plotters = { version = "0.3", features = ["chrono", "all_series"] }
plotters-iced = "0.10"
iced = { version = "0.12", features = ["canvas", "tokio"] }
bytemuck = "1.16"
